# Generated by Django 3.0.7 on 2020-07-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='directory',
        ),
        migrations.AddField(
            model_name='file',
            name='directory_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
