# Generated by Django 3.0.7 on 2020-07-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200715_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='dir_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]