# Generated by Django 3.0.7 on 2020-07-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_directory_dir_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]