# Generated by Django 3.1 on 2020-08-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_follows_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='directory',
            name='branch',
            field=models.CharField(default='master', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='branch',
            field=models.CharField(default='master', max_length=100),
            preserve_default=False,
        ),
    ]
