# Generated by Django 3.1 on 2020-09-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200819_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('repo_id', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='directory',
            old_name='dir_id',
            new_name='subdir',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='directory_id',
            new_name='subdir',
        ),
        migrations.AddField(
            model_name='file',
            name='path',
            field=models.CharField(default='/', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='branch',
            field=models.CharField(max_length=20),
        ),
    ]
