# Generated by Django 3.1 on 2020-09-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_commit_commit_file_issue_issue_comment_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commit_file',
            name='file',
            field=models.IntegerField(),
        ),
    ]
