# Generated by Django 3.1 on 2020-09-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200914_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='branch',
            field=models.CharField(default='master', max_length=20),
        ),
    ]
