# Generated by Django 3.1.1 on 2020-09-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_commit_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit_file',
            name='code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commit_file',
            name='path',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commit_file',
            name='file',
            field=models.IntegerField(null=True),
        ),
    ]
