# Generated by Django 3.1.2 on 2020-10-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200921_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='fork',
            field=models.IntegerField(null=True),
        ),
    ]
