# Generated by Django 3.1.3 on 2020-11-27 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_pypicredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pypicredential',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
