# Generated by Django 3.1.3 on 2021-02-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201127_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.IntegerField()),
                ('commit_id', models.CharField(max_length=100)),
                ('log', models.TextField()),
                ('status_code', models.IntegerField()),
            ],
        ),
    ]
