# Generated by Django 3.1.3 on 2020-11-27 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pypideploy',
            name='project',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pypideploy',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='pypideploy',
            name='url',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
