# Generated by Django 3.1.3 on 2020-12-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_auto_20201127_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='pypideploy',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pypideploy',
            name='success',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pypideploy',
            name='version',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pypideploy',
            name='project',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pypideploy',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
