# Generated by Django 3.2 on 2021-04-14 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_auto_20201222_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='HerokuDeploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('repo_id', models.IntegerField()),
                ('commit_id', models.UUIDField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
