# Generated by Django 3.1.1 on 2020-10-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('phone', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TwoFAToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('code', models.CharField(max_length=7, unique=True)),
                ('phone', models.TextField()),
            ],
        ),
    ]
