# Generated by Django 3.1.2 on 2020-11-01 06:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_twofa_twofatoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
