# Generated by Django 3.1.1 on 2020-10-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_twofa_twofatoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofatoken',
            name='phone',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
