# Generated by Django 3.1.2 on 2020-10-31 00:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_twofatoken_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
