# Generated by Django 3.1.3 on 2020-11-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_authorizeddevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFAUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
